### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by maxlibin** [PRToken/testPRToken#3]
Description
PlatON releases a community campaign to celebrate the launch of PlatON whitepaper 2.0. By completing the following task you are eligible to share 2500 LAT.

Prize Bounty 2500 LAT (approx. 400 USDT) for the first 100 ### complete submissions

Challenge Description

Complete these 3 tasks to learn about the PlatON Whitepaper 2.0:

Follow PlatON Twitter：@PlatON_Network
Join PlatON Telegram：@PlatONNetwork
Leave a one-sentence comment about your view on the Whitepaper 2.0.
Submission Requirements Please submit a document or a screenshot demonstrating the completion of each task.

All bounty submissions must be received no later than 11:59 PM UTC on October 15th, 2021, or earlier.

Judging Criteria Winners will be chosen based on the first 100 valid submissions. We will consider the timestamp of the submission.

Winner Announcement Date Winners will be announced the week of October 15th. Payout will happen within 7 business days after the winners are announced. Make sure you input your l LAT address to be sure to receive payouts.

Questions? Join the PlatON Discord Server or contact telegram admin if you have any questions. We are also holding live ask-me-anything sessions every Friday.

**Comment by Davidminbank** [comment]
test comment

**Comment by Davidminbank** [comment]
test comment 2

**Comment by Davidminbank** [comment]
test comment 3

**Comment by Davidminbank** [comment]
test comment 4

**Comment by Davidminbank** [comment]
test comment 5

**Comment by Davidminbank** [comment]
test comment 5

**Comment by Davidminbank** [comment]
test comment 5

**Comment by Davidminbank** [comment]
sdsd

**Comment by Davidminbank** [comment]
sdsd

**Comment by Davidminbank** [comment]
sdsd

**Comment by Davidminbank** [comment]
sdsd

**Comment by Davidminbank** [comment]
sdsd

**Comment by Davidminbank** [comment]
haha

**Comment by Davidminbank** [comment]
david

**Comment by Davidminbank** [comment]
ok test comment

**Comment by Davidminbank** [comment]
haha

**Comment by Davidminbank** [comment]
This issue has assigned to Davidminbank

**Comment by Davidminbank** [comment]
This issue has assigned to maxlibin

**Comment by Davidminbank** [comment]
This issue has assigned to @Davidminbank

**Comment by Davidminbank** [comment]
This issue now has bounty price of 10 ADA attached to it

**Comment by Davidminbank** [comment]
This issue has assigned to @maxlibin

**Comment by kevin-prtoken** [comment]
This is interesting!
