### ISSUE TITLE
David test add bounty

### ISSUE THREAD

**Issue by Davidminbank** [PRToken/testPRToken#4]
David test add bounty for issue

**Comment by Davidminbank** [comment]
This issue now has bounty price of 14 ADA attached to it

**Comment by Davidminbank** [comment]
This issue now has bounty price of 13 ADA attached to it

**Comment by Davidminbank** [comment]
This issue now has bounty price of 20 ADA attached to it

**Comment by prtokenio** [comment]
This issue now has bounty price of 30 ADA attached to it

**Comment by prtokenio** [comment]
This issue now has bounty price of 20 ADA attached to it

**Comment by Davidminbank** [comment]
This issue has assigned to @Davidminbank
